### ISSUE TITLE
eval script not working

### ISSUE THREAD

**Issue by Claessens14** [Claessens14/pirlnav-fork#1]
in bash running.. 
```
./scripts/run/run-objectnav-il-eval-powerPC.sh
```

generates the following habitat-sim error
```
WB:                                                                                                                                                                                
  ENTITY:                                                                                                                                                                          
  GROUP:                                                                                                                                                                           
  PROJECT_NAME:                                                                                                                                                                    
  RUN_NAME:                                                                                                                                                                        
WRITER_TYPE: tb                                                                                                                                                                    
2023-02-01 22:13:49,243 Initializing dataset ObjectNav-v2                                                                                                                          
2023-02-01 22:13:51,770 Initializing dataset ObjectNav-v2                                                                                                                          
2023-02-01 22:13:53,583 initializing sim Sim-v0                                                                                                                                    
Process ForkServerProcess-1:                                                                                                                                                       
Traceback (most recent call last):                                                                                                                                                 
  File "/home/l/leil/claess14/.conda/envs/pirlnav-v3/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap                                                            
    self.run()                                                                                                                                                                     
  File "/home/l/leil/claess14/.conda/envs/pirlnav-v3/lib/python3.8/multiprocessing/process.py", line 108, in run                                                                   
    self._target(*self._args, **self._kwargs)                                                                                                                                      
  File "/home/l/leil/claess14/.conda/envs/pirlnav-v3/lib/python3.8/contextlib.py", line 75, in inner                                                                               
    return func(*args, **kwds)                                                                                                                                                     
  File "/gpfs/fs0/scratch/l/leil/claess14/pirlnav/habitat-lab/habitat/core/vector_env.py", line 233, in _worker_env                                                                
    env = env_fn(*env_fn_args)                                                                                                                                                     
  File "/gpfs/fs0/scratch/l/leil/claess14/pirlnav/habitat-lab/habitat/utils/env_utils.py", line 32, in make_env_fn                                                                 
    env = env_class(config=config, dataset=dataset)                                                                                                                                
  File "/gpfs/fs0/scratch/l/leil/claess14/pirlnav/pirlnav/environment.py", line 11, in __init__                                                                                    
    super().__init__(config, dataset)                                                                                                                                              
  File "/gpfs/fs0/scratch/l/leil/claess14/pirlnav/habitat-lab/habitat/core/env.py", line 374, in __init__
    self._env = Env(config, dataset)
  File "/gpfs/fs0/scratch/l/leil/claess14/pirlnav/habitat-lab/habitat/core/env.py", line 104, in __init__
    self._sim = make_sim(
  File "/gpfs/fs0/scratch/l/leil/claess14/pirlnav/habitat-lab/habitat/sims/registration.py", line 19, in make_sim
    return _sim(**kwargs)
  File "/gpfs/fs0/scratch/l/leil/claess14/pirlnav/habitat-lab/habitat/sims/habitat_simulator/habitat_simulator.py", line 276, in __init__
    self.sim_config = self.create_sim_config(self._sensor_suite)
  File "/gpfs/fs0/scratch/l/leil/claess14/pirlnav/habitat-lab/habitat/sims/habitat_simulator/habitat_simulator.py", line 309, in create_sim_config
    overwrite_config(
  File "/gpfs/fs0/scratch/l/leil/claess14/pirlnav/habitat-lab/habitat/sims/habitat_simulator/habitat_simulator.py", line 78, in overwrite_config
    raise NameError(
NameError: mass is not found on habitat_sim but is found on habitat_lab config.
                    It's also not in the list of keys to ignore: {'start_rotation', 'is_set_start_state', 'start_position', 'sensors'}
                    Did you make a typo in the config?
                    If not the version of Habitat Sim may not be compatible with Habitat Lab version: ANGULAR_ACCELERATION: 12.56
ANGULAR_FRICTION: 1.0
COEFFICIENT_OF_RESTITUTION: 0.0
HEIGHT: 0.88
IS_SET_START_STATE: False
LINEAR_ACCELERATION: 20.0
LINEAR_FRICTION: 0.5
MASS: 32.0
RADIUS: 0.18
SENSORS: ['RGB_SENSOR', 'DEPTH_SENSOR', 'SEMANTIC_SENSOR']
START_POSITION: [0, 0, 0]
START_ROTATION: [0, 0, 0, 1]

Exception ignored in: <function Simulator.__del__ at 0x7ffdfe2085e0>                                                                                                               
Traceback (most recent call last):                                                                                                                                                 
  File "/home/l/leil/claess14/.conda/envs/pirlnav-v3/lib/python3.8/site-packages/habitat_sim-0.2.2-py3.8-linux-ppc64le.egg/habitat_sim/simulator.py", line 555, in __del__         
    self.close(destroy=True)                                                                                                                                                       
  File "/home/l/leil/claess14/.conda/envs/pirlnav-v3/lib/python3.8/site-packages/habitat_sim-0.2.2-py3.8-linux-ppc64le.egg/habitat_sim/simulator.py", line 131, in close           
    if not self._initialized:                                                                                                                                                      
AttributeError: 'HabitatSim' object has no attribute '_initialized'                                                                                                                
Traceback (most recent call last):
  File "/home/l/leil/claess14/.conda/envs/pirlnav-v3/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/l/leil/claess14/.conda/envs/pirlnav-v3/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/gpfs/fs0/scratch/l/leil/claess14/pirlnav/run.py", line 94, in <module>
    main()
  File "/gpfs/fs0/scratch/l/leil/claess14/pirlnav/run.py", line 42, in main
    run_exp(**vars(args))
  File "/gpfs/fs0/scratch/l/leil/claess14/pirlnav/run.py", line 90, in run_exp
    execute_exp(config, run_type)
  File "/gpfs/fs0/scratch/l/leil/claess14/pirlnav/run.py", line 75, in execute_exp
    trainer.eval()
  File "/gpfs/fs0/scratch/l/leil/claess14/pirlnav/habitat-lab/habitat_baselines/common/base_trainer.py", line 127, in eval
    self._eval_checkpoint(
  File "/gpfs/fs0/scratch/l/leil/claess14/pirlnav/pirlnav/il_trainer.py", line 588, in _eval_checkpoint
    self._init_envs(config)
  File "/gpfs/fs0/scratch/l/leil/claess14/pirlnav/habitat-lab/habitat_baselines/rl/ppo/ppo_trainer.py", line 203, in _init_envs
    self.envs = construct_envs(
  File "/gpfs/fs0/scratch/l/leil/claess14/pirlnav/habitat-lab/habitat/utils/env_utils.py", line 113, in construct_envs
    envs = vector_env_cls(
  File "/gpfs/fs0/scratch/l/leil/claess14/pirlnav/habitat-lab/habitat/core/vector_env.py", line 193, in __init__
    self.observation_spaces = [
  File "/gpfs/fs0/scratch/l/leil/claess14/pirlnav/habitat-lab/habitat/core/vector_env.py", line 194, in <listcomp>
    read_fn() for read_fn in self._connection_read_fns
  File "/gpfs/fs0/scratch/l/leil/claess14/pirlnav/habitat-lab/habitat/core/vector_env.py", line 97, in __call__
    res = self.read_fn()
  File "/gpfs/fs0/scratch/l/leil/claess14/pirlnav/habitat-lab/habitat/utils/pickle5_multiprocessing.py", line 67, in recv
    buf = self.recv_bytes()
  File "/home/l/leil/claess14/.conda/envs/pirlnav-v3/lib/python3.8/multiprocessing/connection.py", line 216, in recv_bytes
    buf = self._recv_bytes(maxlength)
  File "/home/l/leil/claess14/.conda/envs/pirlnav-v3/lib/python3.8/multiprocessing/connection.py", line 414, in _recv_bytes
    buf = self._recv(4)
  File "/home/l/leil/claess14/.conda/envs/pirlnav-v3/lib/python3.8/multiprocessing/connection.py", line 379, in _recv
    chunk = read(handle, remaining)
ConnectionResetError: [Errno 104] Connection reset by peer
Exception ignored in: <function VectorEnv.__del__ at 0x7ffde0d1f310>
Traceback (most recent call last):
  File "/gpfs/fs0/scratch/l/leil/claess14/pirlnav/habitat-lab/habitat/core/vector_env.py", line 592, in __del__
    self.close()
  File "/gpfs/fs0/scratch/l/leil/claess14/pirlnav/habitat-lab/habitat/core/vector_env.py", line 460, in close
    read_fn()
  File "/gpfs/fs0/scratch/l/leil/claess14/pirlnav/habitat-lab/habitat/core/vector_env.py", line 97, in __call__
    res = self.read_fn()
  File "/gpfs/fs0/scratch/l/leil/claess14/pirlnav/habitat-lab/habitat/utils/pickle5_multiprocessing.py", line 67, in recv
    buf = self.recv_bytes()
  File "/home/l/leil/claess14/.conda/envs/pirlnav-v3/lib/python3.8/multiprocessing/connection.py", line 216, in recv_bytes
    buf = self._recv_bytes(maxlength)
  File "/home/l/leil/claess14/.conda/envs/pirlnav-v3/lib/python3.8/multiprocessing/connection.py", line 414, in _recv_bytes
    buf = self._recv(4)
  File "/home/l/leil/claess14/.conda/envs/pirlnav-v3/lib/python3.8/multiprocessing/connection.py", line 383, in _recv
    raise EOFError
```

**Comment by Claessens14** [comment]
name error information
```
MASS                                                                                                                                                                               
mass                                                                                                                                                                               
{'start_rotation', 'start_position', 'is_set_start_state', 'sensors'}                                                                                                              
32.0  
```

**Comment by Claessens14** [comment]
## Resolution

```
commented out NameError() function on line 78
/gpfs/fs0/scratch/l/leil/claess14/pirlnav/habitat-lab/habitat/sims/habitat_simulator/habitat_simulator.py
```

**Comment by BigTree765** [comment]
@Claessens14 I have the same issue， have you solved it？

**Comment by Claessens14** [comment]
did the solution I posted above not work for you? Sorry it has been a while since I have dealt with this problem, so likely forget.
